name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        cd ./client
        npm install
    - name: Actually Build
      run: |
        cd ./client
        npm run build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: 'Test-Artifact'
        # A file, directory or wildcard pattern that describes what to upload
        path: './'
